### ISSUE TITLE
Support SSL Encryption

### ISSUE THREAD

**Issue by andrewmunro** [lovoo/goka#101]
Hi, looking through the library it looks like it doesn't support encrypted traffic to kafka:

https://docs.confluent.io/current/kafka/authentication_ssl.html

Would this be difficult to implement?

**Comment by db7** [comment]
Goka does not implement the communication with Kafka. For that we employ existing libraries. By default, Goka uses [sarama](https://github.com/Shopify/sarama), which is pure Go and does support SSL connections.

As an alternative, you may also use [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go), which uses `librdkafka` underneath and should support virtually everything you'd need. Although our [wrapper around confluent's library](/lovoo/goka/tree/master/kafka/confluent) isn't complete yet, it shouldn't be too hard to finish it.

**Comment by andrewmunro** [comment]
I see that it's possible with sarama, but the question was more around whether goka will let me configure the TLS options passed to sarama?

It may be possible using `goka.WithProducerBuilder()` and `goka.WithConsumerBuilder()`, I'll have a play when I have time. If I get a decent example I'll post back here.

**Comment by db7** [comment]
Yes, you can configure sarama with the builders. Check [this snippet](https://github.com/lovoo/goka/wiki/Tips#passing-options-to-sarama) for an example.

**Comment by andrewmunro** [comment]
Perfect this is exactly what I needed. Thanks @db7

**Comment by db7** [comment]
@frairon ^
