### ISSUE TITLE
Getting error from Emitter

### ISSUE THREAD

**Issue by jbpin** [lovoo/goka#103]
Hi guys. Its a simple question about how to get Error when using Emit and EmitSync. Using promise it looks like you never treat the returning error

https://github.com/lovoo/goka/blob/b7b94ac132a786822c94040751d1c9955a441ea2/emitter.go#L62-L64

https://github.com/lovoo/goka/blob/b7b94ac132a786822c94040751d1c9955a441ea2/emitter.go#L76-L78

**Comment by frairon** [comment]
Hi jbpin, absolutely! Nice catch. Will fix it.

**Comment by frairon** [comment]
Something like this?
https://github.com/lovoo/goka/pull/104

**Comment by db7** [comment]
Resolved by #104
