### ISSUE TITLE
How to create table based on a different key

### ISSUE THREAD

**Issue by MahlerFive** [lovoo/goka#123]
I'm new to goka and trying to figure out the best way to create a table based on a different key than the events I'm consuming.

For example, assume I'm consuming events that look like:
```
{
  "client_id": "abc123",
  "business_id": "def456",
  "timestamp": "2018-01-01 01:23:45"
}
```

The key on these events is the `client_id`. What I want to do is consume these events and create a table that tracks the latest timestamp by `business_id`. So in that case, my new key would be `business_id`.

There are two options I see:
1) Consume the original events and emit rekeyed versions of them to a new topic, then consume the new topic and update the table based on those.
2) Consume the original events and use `Context.Lookup` and `Context.Emit` or `Context.Loopback` (not sure which one to use) in order to specify the key based on `business_id`.

Which of these options is preferred, or is there another better option?

**Comment by db7** [comment]
You are right. Solution 1 is to have 2 processors and solution 2 is to loop the message to the right key before changing that table.

Solution 1 is safer, but you'll have to write more code.

Solution 2 would use `Loopback`. You just have to be careful if you'd like to process multiple topics. You'd have to do some extra work to pass both types (the original stream and the new stream) into the loop. Plus, you have to be careful that the other topic would also use the same keys. That said, we use loopback a lot.

In case you have just one input stream, solution 2 would look like this:
```go
g := DefineGraph(group,
  goka.Input(topic, myCodec, func(ctx goka.Context, m interface{}) {
    key := m.(*mytype).BusinessId
    ctx.Loop(key, m)
  }),
  goka.Loopback(myCodec, func(ctx goka.Context, m interface{}) {
    // real code
  }),
  goka.Persist(myTableCodec),
)
```

Note that if you want to repartition the stream, you need to use solution 1, ie, using `Emit` instead of `Loopback`. That's because the loopback topic has to have the same number of partitions as the input streams.

**Comment by MahlerFive** [comment]
So my case is actually a bit more complicated in that I want to consume 2+ input topics, each of which use a different key, and which have different numbers of partitions, but I want all of these to contribute to the group table. In that case it sounds like using `Loopback` is not possible or a lot harder.

What I'm trying to understand is how best to accomplish what I want. I was originally just going to use sarama to consume from each input topic and output a rekeyed version of that topic so that all my topics are keyed by `business_id`. Then I would create a graph like this:

```
g := DefineGraph(group,
  goka.Input(topic1, myCodec, func(ctx goka.Context, m interface{}) {
    // update timestamp to latest for this event type
    if val := ctx.Value(); val != nil {
      state = val.(*myStateStruct)
    }
    state.event1Timestamp = msg.Timestamp
    ctx.SetValue(state)
  }),
  goka.Input(topic2, myCodec, func(ctx goka.Context, m interface{}) {
    // update timestamp to latest for this event type
    if val := ctx.Value(); val != nil {
      state = val.(*myStateStruct)
    }
    state.event2Timestamp = msg.Timestamp
    ctx.SetValue(state)
  }),
  goka.Persist(myTableCodec),
)
```

For the above approach, do my rekeyed input topics need to have the same number of partitions? From the docs it seems so, but not sure why that would be necessary.

The other approach I was thinking was doing the rekeying on the fly somehow with `goka` but I'm not exactly sure how. Maybe something like this would work? If not is there a better way?

```
g := DefineGraph(group,

  goka.Input(topic1, myCodec, func(ctx goka.Context, m interface{}) {
    // rekey
    ctx.Emit(topic1Rekeyed, m.(*myStateStruct).BusinessID, m)
  }),
  goka.Output(topic1Rekeyed, myCodec),
  goka.Input(topic1Rekeyed, myCodec, func(ctx goka.Context, m interface{}) {
    // update timestamp to latest for this event type
    if val := ctx.Value(); val != nil {
      state = val.(*myStateStruct)
    }
    state.event1Timestamp = msg.Timestamp
    ctx.SetValue(state)
  }),

  goka.Input(topic2, myCodec, func(ctx goka.Context, m interface{}) {
    // rekey
    ctx.Emit(topic2Rekeyed, m.(*myStateStruct).BusinessID, m)
  }),
  goka.Output(topic2Rekeyed, myCodec),
  goka.Input(topic2Rekeyed, myCodec, func(ctx goka.Context, m interface{}) {
    // update timestamp to latest for this event type
    if val := ctx.Value(); val != nil {
      state = val.(*myStateStruct)
    }
    state.event2Timestamp = msg.Timestamp
    ctx.SetValue(state)
  }),

  goka.Persist(myTableCodec),
)
```

**Comment by db7** [comment]
> So my case is actually a bit more complicated in that I want to consume 2+ input topics, each of which use a different key, and which have different numbers of partitions, but I want all of these to contribute to the group table. In that case it sounds like using Loopback is not possible or a lot harder.

Right.

> For the above approach, do my rekeyed input topics need to have the same number of partitions? From the docs it seems so, but not sure why that would be necessary.

Yes. Input streams must have the same number of partitions and use the same key space. If keys are user_id, then all events for the same user_id end up in the same partition and are processed in the same processor instance.

The `Loopback` solution above is a kind of a hack. The clean way how to do that is with solution 1, where the input streams are first rekeyed and repartitioned by a preprocessor that emits the messages with the right key into a topic with the right number of partitions.

> The other approach I was thinking was doing the rekeying on the fly somehow with goka but I'm not exactly sure how. Maybe something like this would work? If not is there a better way?

I think you'll have more headaches with that than with writing the separate processors.

I'd suggest you to start with the simplest approach: create preprocessors for rekeying your input streams. The preprocessors are stateless and won't be complicated. You can run the preprocessors together with your stateful processor in the same Go program.  And if you don't want to manually create the topics with the right number of partitions, you can use the [topic manager](https://godoc.org/github.com/lovoo/goka/kafka#TopicManager) in your program (needs the Zookeeper connection string).

**Comment by MahlerFive** [comment]
Thanks for your help so far!

If I was to do the preprocessing with `goka` instead of using sarama like I was planning, what would be the proper 'goka` way to do this? Just create a separate graph for each input topic, define an output topic for each, then have a final graph using those rekeyed topics as input?

something like:

```
g1 := DefineGraph(rekeyGroup1,
  Input(topic1 ...),
  Output(rekeyedTopic1 ...)
)

g2 := DefineGraph(rekeyGroup2,
  Input(topic2 ...),
  Output(rekeyedTopic2 ...)
)

g3 := DefineGraph(group,
  Input(rekeyedTopic1 ...),
  Input(rekeyedTopic2 ...),
  Persist( ... )
)
```

**Comment by db7** [comment]
Yes, that looks good. 

Now, you have to create 3 processors, one for each processor group. Goka does not provide any tool to make this easier yet. So I'd do something like this:

```go
for _, g := range []goka.GroupGraph{ g1, g2, g3 } {
  p, err := goka.NewProcessor(brokers, g1)
  if err != nil {
    panic(err)
  }
  go p.Start()
}
```

You also need to store all these processors in a slice and stop them if SIGINT/SIGTERM arrives.

If you have suggestions how this could be simpler, please let us know. We are actually planning to replace the `Start()` and `Stop()` methods of processors with a `Run(context.Context)`. That should simplify a bit managing multiple processors in the same program.
