### ISSUE TITLE
Prevent offset commit in case of panic

### ISSUE THREAD

**Issue by StevenJohnston** [lovoo/goka#129]
Is it possible to prevent a consumer from committing offset after it has received a record? In my callback function I would like to error out so that if the consumer fails, a future consumer will pick up the record it was on.

**Comment by frairon** [comment]
If I understand you correctly, you want to ignore a message but continue with the rest and let the "failed message" be consumed by another consumer. 
If that is your case, then I'd say accomplishing it is not straight-forward. In Kafka, messages are considered sequential with increasing offsets, i.e. if you do not acknowledge a message, you will not get the next one. If you do want to ignore a message or want to reprocess it, you would have to store it somewere or push it to another topic.
Technically it should be possible to reprocess one failed message, if you know it's "topic-partition-offset"-identification and create a low-level consumer starting from that offset and stopping after the first message, but this is probably not the best design and not how goka works.

Anyway... If above is *not* what you want, and you simply want to stop after a message couldn't be processed, you can simply call `ctx.Fail("whatever reason")` and the whole processor will shut down. The message that caused the stop will not be acknowledged, so after restarting the processor or a future consumer it will again receive the message where the former processor failed.

**Comment by StevenJohnston** [comment]
I tried ctx.Fail and let my service error out. After replacing it with a new instance it continued on the next message. It appears my callback is triggering a defer instantiated right before it was called. This defer ensures the offset is committed. 
  
https://github.com/lovoo/goka/blob/4037dcdd06cce190f49bfe676579075396eb123d/processor.go#L723-L725
https://github.com/lovoo/goka/blob/be1af5be4bdc8d61e12ddade27887271cbfd1a48/context.go#L296-L301

Since done is set true, processors will always commit offset even upon panic.

https://github.com/lovoo/goka/blob/be1af5be4bdc8d61e12ddade27887271cbfd1a48/context.go#L308-L329

**Comment by db7** [comment]
That is an issue, @StevenJohnston. Thanks for reporting. I'll come up with a test case and a fix as soon as possible.

**Comment by db7** [comment]
@StevenJohnston, we merged a fix with PR #130.
