### ISSUE TITLE
How to initialize consumer group at offset start.

### ISSUE THREAD

**Issue by StevenJohnston** [lovoo/goka#132]
I've noticed that a new consumer group does not consumer earlier messages. Its nice that a consumer group will retrieve missed messages while it was down, but this requires that the consumer group was connected at an earlier time. Is it possible that when a new group is defined, it starts at the first message in a topic?

**Comment by db7** [comment]
Yes, that is possible. You need to configure the consumer builder. Something like this should do the job:
```go
import "github.com/lovoo/goka"
import "github.com/lovoo/goka/kafka"

config := kafka.NewConfig()
config.Consumer.Offsets.Initial = -2
proc, err := goka.NewProcessor(brokers, gg,
     goka.WithConsumerBuilder(kafka.ConsumerBuilderWithConfig(config)))
```

**Comment by StevenJohnston** [comment]
Thank you. 
```
config.Consumer.Offsets.Initial = kafka.OffsetOldest
```
