### ISSUE TITLE
Question: How to create tables with log compaction

### ISSUE THREAD

**Issue by edgar86cru** [lovoo/goka#138]
Hi, I try to follow the tips on the wiki about how to create tables with log compaction.
I'm using the method "Using TopicManager to create table topics" but when I go to check the topic level configuration my table doesn't have the conf "cleanup.policy=compact".
I saw that the tips in the wiki were updated the last time on 25th of February, are they still valid??
Thank you
Edoardo

**Comment by SamiHiltunen** [comment]
Hey, could it be that the topic already existed before you attempted to create it using TopicManager? TopicManager only creates a topic with the correct configuration if it doesn't already exist. It doesn't reconfigure an existing topic.

If you have automatic topic creation (`auto.create.topics.enable=true`) on in Kafka, it could be that the topic was created with the default configuration of Kafka when someone tried to read from the topic.

**Comment by SamiHiltunen** [comment]
Good to hear that the problem was found, I'll close the ticket in this case.
