### ISSUE TITLE
consistency views and processors at  N-nodes

### ISSUE THREAD

**Issue by scarbo87** [lovoo/goka#143]
Hi, how do you achieve consistency views and processors at  N-nodes? Views can consume messages from the topic-tables at different rates.

**Comment by db7** [comment]
Each processors in the same processor group can only modify some partitions in the group table, so there is no concurrency between them.

Views consume the group tables at different rates, yes. They are eventually consistent.

**Comment by scarbo87** [comment]
@db7, thanks for the answer.
if one of the view is slowly consuming from kafka, then reading from it will not be consistent? How do you solve this problem in production?

**Comment by db7** [comment]
So far we don't expose the record timestamp of Kafka in the views. Would that be a better solution? @SamiHiltunen

**Comment by scarbo87** [comment]
Should the user receive version/timestamp label from the processor and store it?
@db7

**Comment by scarbo87** [comment]
@db7, WOW, thank you very much for your answer!

**Comment by db7** [comment]
@scarbo87 then I'm closing this issue. If you still have problems with that please reopen it.
