### ISSUE TITLE
Removal of db7/kazoo-go and subsequent repo deletion breaks previous builds

### ISSUE THREAD

**Issue by dan-compton** [lovoo/goka#154]
[This](https://github.com/lovoo/goka/commit/abc051cf0cc83b259af7f5caad425257f9bca510#diff-5635ef3040b9420de577e65fdfff1083) change made by contributor @db7 and the subsequent removal of github.com/db7/kazoo-go repository breaks glide/dep vendored versions of lovoo/goka due to inability to fetch db7/kazoo-go.  Broken version below:
 
```
- name: github.com/lovoo/goka
  version: d58a3143ca343a51a72459a6de8ad138c219c546
 ```
API changes likely make upgrading difficult.

**Comment by dan-compton** [comment]
closing this because I've fixed it with a glide mirror

**Comment by db7** [comment]
@dan-compton thanks for reporting. The changes that were in db7/kazoo-go are merged upstream, so I updated goka accordingly to use that repo instead. I probably shouldn't have delete my fork though. I reforked the repo in the hope that your build process passes again. Could you check that please? Or if you have another suggestion, let me know.

**Comment by dan-compton** [comment]
@db7 We're sticking with the fork + glide mirror until we update goka as the relevant changes to tooling have already been merged internally.  Thanks though.  As for others, it will work fine as long as the commit sha is the same.
