### ISSUE TITLE
aggregate table topics

### ISSUE THREAD

**Issue by yuhui-lin** [lovoo/goka#161]
Hey, I am trying to re-partition and aggregate a table topic using goka. but it seems that it's difficult to do so.

by looking at kafka stream, they mentioned `Old values are necessary for implementing aggregate functions.` they seems to materialize the entire input table before running the callback. 
https://issues.apache.org/jira/browse/KAFKA-2984

to make it easier to do aggregation, it may be good to add a new edge to listen on a table topic. this is similar to add a callback to Join Edge.
```
func InputTable(topic Table, c Codec, cb ProcessTableCallback) Edge
type ProcessTableCallback func(ctx Context, msgNew interface{}, msgOld interface{})
```
any thoughts?

**Comment by db7** [comment]
I think I didn't understand your use case, but the first thing that comes to my mind is that you can consume the table as a stream topic via normal input edge and store the aggregation in the group table, something like,
```
myTable := "table123"
gg := goka.DefineGroup(group,
  goka.Input(goka.Stream(myTable), codec, cb),
  goka.Persist(codec),
)

func cb(ctx Goka.Context, new interface{}) {
  old := ctx.Value()
  result := process(old, new)
  ctx.SeValue(result)
}
```

Would that help you? If not, can you give us some more details?

**Comment by yuhui-lin** [comment]
yes, this should help with aggregating table topic. 
I have another use case: I want to inner-join two table topics with the same key giving a join function `joinFunc(row1, row2)`.  these two tables are big and I may not want to create views. 
I think one option is creating two inputs on each topic. I'll have to look up the other table in each input callback function. but goka doesn't seem to allow same topic as input and join #95. so I have to create one processor for each input table, as followed. but in this way we will have synchronization issue and the result may not be consistent.
```go
g1 := goka.DefineGroup(group,
  goka.Input(goka.Stream(myTable1), codec, cb1),
  goka.Join(goka.Table(myTable2), codec),
  goka.Output(goka.Stream(resultTable), codec),
)
g2 := goka.DefineGroup(group,
  goka.Input(goka.Stream(myTable2), codec, cb2),
  goka.Join(goka.Table(myTable1), codec),
  goka.Output(goka.Stream(resultTable), codec),
)
```

the other option I can think of is similar to how kafka KTable handles join. we first load the input table(everything before committed offset) into levelDB, then run the input callback and update the levelDB store in callback. this way we only need one processor and don't have the synchronization problem. we've implemented the join in this way and it seems to work fine. that's why I think it might be good to have  a new edge for table topic.
hope I made things clear.

**Comment by yuhui-lin** [comment]
thanks for the example. it looks good. but I would make a little change to `cb1`:
```
func cb1(ctx goka.Context, m interface{}) {
  v := ctx.Value().(*joinedFields) // new(joinedFields) if v == nil
  v.row1 = m
  ctx.Emit(..., ctx.Key(), joinFunc(v.row1, v.row2))
  ctx.SetValue(v)
}
```
I have two questions about this approach:
- it may also have consistency issue assuming cb1 and cb2 running on separate goroutines. for example, cb1 gets suspended after `ctx.Value()`. then, cb2 does `ctx.Value` and also writes the new row2 to the group table (ctx.SetValue). now the cb1 holds out of date value `v` and it's going to overwrite new row2 with old row2 in group table. is this problem likely to happen in goka?
- compared to what I proposed, this method create an extra "buffer" table topic. it literally duplicates myTable1 and myTable2 in kafka which may not be ideal.

we have use cases related to aggregate/join/foreign-key-join multiple table-like topics. `KTable` from kafka stream DSL seems a good fit for us. but we'd like to explore using goka for this. for `groupby` and `join` operation of `KTable`, kafka stream updates local store and provides both old and new values, as you can see in https://github.com/apache/kafka/blob/46e8081f9cae24f5edbfa2099e317a33e531d2fb/streams/src/main/java/org/apache/kafka/streams/kstream/internals/KTableSource.java#L96. 
do you think it's appropriate to add more support for table-like topic in goka?

**Comment by db7** [comment]
> it may also have consistency issue assuming cb1 and cb2 running on separate goroutines. for example, cb1 gets suspended after ctx.Value(). then, cb2 does ctx.Value and also writes the new row2 to the group table (ctx.SetValue). now the cb1 holds out of date value v and it's going to overwrite new row2 with old row2 in group table. is this problem likely to happen in goka?

No, it won't happen. Table1 and Table2 have the same keys and the same number of partitions. So all records of partition 0 of both tables are processed by a single goroutine that reads these records out of one input channel.

> compared to the approach I mentioned above, this method create an extra "buffer" table topic. it literally duplicates myTable1 and myTable2 in kafka which may not be ideal.

I don't think that's a major issue.



> do you think it's appropriate to add more support for table-like topic in goka?

Yes, but I'd suggest to add that as a sub package library on top of the low-level ProcessorCallbacks. We have internally some libraries that provide helpers to create the edges and wrap the ProcessorCallbacks.

Check the windowing discussion in ticket #99. I think the approach how to implement that is related. 

---

Another thing that came to my mind. If you are joining the tables, you want to process every single record in the topics. By default, Goka starts consuming streams at the current HWM, not at the beginning. In your use case, you'll need to change this initial offset (of sarama). You can do that by passing a config to the ConsumerBuilder. See #132.

**Comment by yuhui-lin** [comment]
thanks @db7 . I'll go through #99 and think about the implementation.

**Comment by db7** [comment]
@yuhui-lin I'll close this issue for now. Reopen it if necessary.
