### ISSUE TITLE
Prevent offset commit when calling log.Fatalf in callback

### ISSUE THREAD

**Issue by antonin07130** [lovoo/goka#167]

**Comment by frairon** [comment]
Hi antonin07130,

thanks for the report, can you elaborate on the question or the bug report, please? 
From the title I would assume that you're having trouble with the offset commit whenever a panic happens during processing of the message.
Goka makes sure to not commit any offsets whenever there's an error in one of the operations inside the message processing callback. 
If it does, it's definitely a bug and it would be very helpful to get an example to reproduce that behavior.

Thanks

**Comment by frairon** [comment]
I'll close it as it doesn't seem to be an issue anymore.
