### ISSUE TITLE
Rebalancing error

### ISSUE THREAD

**Issue by 5cmpersec** [lovoo/goka#172]
We observe some errors in the log due to rebalancing errors.
It seems that the processor tried to restart several times

```
2019/02/15 06:10:20 Processor: dispatcher stopped
2019/02/15 06:10:20 failing: kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
<200 error messages more ...>
<restart>
2019/02/15 06:10:21 error running processor: Errors:
* kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
```

The only way to recover from this error is to shut down the instances and start it again.

**Comment by frairon** [comment]
I'm not sure I understand the question here.
If there is an error communicating with Kafka (e.g. one broker crashed, so the leader for some partitions is not available), then the goka processor shuts down.
I have not seen this error message on a healthy cluster. If that is the case for you, then this might be an issue (though with kafka configuration probably and not goka itself).

**Comment by 5cmpersec** [comment]
You are right.
This issue happens when one partition is i/o timeout, so goka processor stopped.

Thank you.

**Comment by frairon** [comment]
No problem :) 
So the current behavior is intended and actually not an error, right?
If you agree we could close the issue.

**Comment by 5cmpersec** [comment]
Yeah, I closed this ticket. Thank you.
