### ISSUE TITLE
Why append "-table" to topic name?

### ISSUE THREAD

**Issue by andrewmunro** [lovoo/goka#174]
Just a query, what is the reasoning behind suffixing to the topic name that is passed? 

This prevents us using views with compacted topics that were generated by other (non-goka) applications...

**Comment by frairon** [comment]
Hi andrewmunro,

the reasoning I guess is simply convenience. The processor is identified by it's group name, thus its group table name is suffixed -table. If there's a need to overwrite that behavior I think it's quite easy to add an option here.
What is not clear from your question is, why you can't have a view on a compacted topic without the suffix?
It's totally fine to create a view using `goka.View(<brokers>, "compacted-topic", <codec>)`. It won't add the "-table"-suffix here and it should just work.

**Comment by andrewmunro** [comment]
Haha silly me didn't realise you can just do`goka.Table("topic")` (I was doing `goka.GroupTable(goka.Group("topic"))` before.

**Comment by frairon** [comment]
No worries :). I think the names are a bit misleading here, because the `goka.Table` and `goka.Topic` are just casting the types and `goka.GroupTable` actually changes the value.
