### ISSUE TITLE
Question: are processor instances scaled automatically?

### ISSUE THREAD

**Issue by activeshadow** [lovoo/goka#179]
I'm looking to use `goka` to help process large amounts of incoming messages against state. In reading the documentation, I've yet to get a good understanding of how scaling processors should occur.

For example, is the `ProcessCallback` function provided as part of the `Input` edge of a `ProcessorGroup` scaled automatically to the same number of partitions the Kafka topic provided to the `Input` edge has?

Also, is a `goka` `ProcessorGroup` synonymous to a Kafka Consumer Group, in that if I was running a `ProcessorGroup` per microservice in my Kubernetes cluster and had multiple replicas of the microservice deployed, each microservice would get a copy of each message in the Kafka topic associated with the microservice's `ProcessorGroup` (which is **not** what I would want)?

In general, what's the appropriate way to scale `goka` processor instances to handle fluctuations in incoming messages? I'm somewhat new to Kafka in general, so perhaps I'm missing something obvious that is making me look at this incorrectly?

Thanks in advance for any advice and thanks for a really slick library.

**Comment by db7** [comment]
@activeshadow, there is no automatic scaling mechanism. Usually, one runs processors and services in Kubernetes and uses other means to start multiple instances of them. Note though that the scalability of the processors is limited by the number of partitions that your topics have (not a Goka limitation, but a fact of Kafka-based applications).

If you have little state in the processors, then you probably won't have issues using the CPU load or memory usage to trigger an increase of instances in your infrastructure. The applications I worked with used to have large processor state and where not easy to autoscale.

**Comment by activeshadow** [comment]
@db7 thank you for taking the time to respond! So if I understand correctly, something like Kubernetes deployment replicas is the way to scale. This, in turn, must mean that a `goka` `ProcessorGroup` is **not** synonymous to a Kafka `ConsumerGroup`, and as such scaling a `goka` `ProcessorGroup` will **not** result in each instance getting a copy of each message in a Kafka topic.

Can you confirm that having multiple instances of the same `ProcessorGroup` will **not** result in each instance processing each message in a Kafka topic?

Thanks again!

**Comment by db7** [comment]
ProcessorGroup in goka is pretty much the same as a Kafka ConsumerGroup.

If you start multiple consumers with the same consumer group, then they won't consume the same messages. So if you start multiple processors with the same "processor group", they won't consume the same message. Except if one of them fails and the other takes over, but that is the same in any Kafka consumer.

**Comment by activeshadow** [comment]
Ah... I'm starting to see it now (I'm new to Kafka, surprisingly enough). The idea of a consumer group is just a group name a consumer associates itself with when connecting to Kafka.

Anyway, this helps a ton. Thank you again so much for taking the time to reply back to me and for developing and maintaining such a slick library.

**Comment by db7** [comment]
No problem. If you are into slack, `gophers.slack.com` has a `#goka` and a `#kafka` channel for discussions -- not sure if it is faster than here, though.

**Comment by pachmu** [comment]
@db7 question related to this theme. If I have two instances of my microservice, each processes the same topic with one partition, I guess it will be one processor per service. So as I understand if both instances use the default context storage, they will have different values in their contexts. Is it true?
