### ISSUE TITLE
Seek in memory.go appears to be broken

### ISSUE THREAD

**Issue by abhishekrb19** [lovoo/goka#181]
`Seek()` in `memory.go` appears to be broken. It would always return `true`, regardless of the key being seeked for. 
```golang
func (i *memiter) Seek(key []byte) bool {
	seek := make(map[string][]byte)
	keys := []string{}
	for k, v := range i.storage {
		if strings.Contains(k, string(key)) {
			keys = append(keys, k)
			seek[k] = v
		}
	}
	i.current = -1
	i.storage = seek
	i.keys = keys
	return !i.exhausted()
}
```

`i.exhausted()` will always return `false` from `Seek()` because current is being overwritten to -1. Also, should the check for keys actually be `strings.HasPrefix(k, string(key))` and not `strings.Contains(k, string(key))`?

**Comment by frairon** [comment]
Hi @abhishekrb19, 
thanks for reporting the issue!
I'll have a look on that. Can't promise anything, but I'll try to do it soonish. 
As usual, improvements and PRs are very welcome :) 

Cheers

**Comment by db7** [comment]
Actually, there is an unmerged branch by Sami that should have fixed these issues. May make sense to check that out.

**Comment by db7** [comment]
@frairon can you check the PR by Sami? It fixes this issue.

**Comment by frairon** [comment]
seems fixed.
