### ISSUE TITLE
How can I config multiple consumer for 1 Topic

### ISSUE THREAD

**Issue by weburnit** [lovoo/goka#184]
Hello dears,
I've tried but there's only one Consumer run, others don't have any effects.
Are there any specific configuration for Goka?
Thanks

**Comment by frairon** [comment]
Hi Paul, 

I'm not sure I understand what you mean with "multiple consumer". 
When using goka, you can create either an Emitter (that just sends messages), a Processor (that consumes events, persists state in a table and emits messages) as well as a View (read-only access to a processor's state table). 
If e.g. an input topic has multiple partitions, which it usually has, then you'll consume them in parallel. 
If you spin up two instances of a processor having the same group name, they'll be assigned their fair share of partitions by kafka.

Check out the blog post linked in the Readme and the examples in Goka to get started with Goka. 
If you have further questions, feel free to join the Goka channel in the Gophers workspace on slack.

Cheers, Franz

**Comment by weburnit** [comment]
your comment is great enough to close my issue
