### ISSUE TITLE
Update Kafka consumer group library

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#187]
The original Sarama library now support Kafka consumer groups out of the box, and `sarama-cluster` library is officially deprecated: https://github.com/bsm/sarama-cluster#deprecation-notice

Therefore, it would be great to replace sarama-cluster and use the original Sarama library for consumer group handling.

**Comment by frairon** [comment]
Absolutely, I agree. I actually started a branch to migrate that some weeks ago, but haven't found the time to continue yet. if you want to start working on that let me know and I can push the branch.

**Comment by frairon** [comment]
I'll close that for now as we're upgrading that right now. As soon as we're on a stable state we'll create a new issue to discuss details/problems with the upgrade
