### ISSUE TITLE
Question: Rebalancing callback?

### ISSUE THREAD

**Issue by gmather** [lovoo/goka#195]
I have a use case where I'm using the UpdateCallback in a Processor to get access to the Group table partition data. If a rebalance happens is there any way currently to know which partitions you are losing? I don't think I can see a way of making that work with processor options easily. If not, would adding a callback to the storageProxy or around there make sense? I'm happy to contribute if something like this makes sense.

**Comment by db7** [comment]
Perhaps the most elegant way is to add a new callback for new partition assignments.

If you want to add something like that you could add a new processor option for a RebalanceCallback and then call the function inside the rebalance function [here](https://github.com/lovoo/goka/blob/dfc3e6211fa3d517ff9ffee0d7abe2b799251b70/processor.go#L659).

A not so elegant solution is to wrap the storage and the storage builder. There you'd see which storage partitions are being opened and closed.

I guess that the callback is easy enough and makes sense to implement. I'd be happy to review your PR.

**Comment by gmather** [comment]
Thanks for looking.
