### ISSUE TITLE
Kafka-streams API support

### ISSUE THREAD

**Issue by smaldeniya** [lovoo/goka#201]
HI Can I know whether this library supports for [kafka-streams](https://kafka.apache.org/documentation/streams/) API ?

**Comment by db7** [comment]
No. Still, you connect Kafka Streams with Goka, eg, a processor written in Kafka Streams or KSQL write to a table and a Goka View provides access to that table within a service. You just need to use the same marshalers.

**Comment by smaldeniya** [comment]
@db7 sorry did not get it exactly. do you have any example code I can look into.

Thanks a lot

**Comment by db7** [comment]
I don't have any code example for that, sorry. What I meant is, you can connect consumers and producers written in any language with Kafka as long as every consumer/producer knows how to marshal the messages.

Take a look in this example of Goka: https://github.com/lovoo/goka/tree/master/examples/3-messaging

Here you could have some of the processors written with Kafka Streams and others with Goka.
