### ISSUE TITLE
High Watermark (hwm) in statistics

### ISSUE THREAD

**Issue by cioboteacristian** [lovoo/goka#205]
I am trying to push Goka statistics to prometheus (and later on plot them on Grafana). I want to plot how far behind my consumers are, by looking at the offset and high watermark, however, the result is always 0 lag, even though I actually simulated lag (and running kafka-console-consumer shows me that my consumer groups actually have lag). Even using the provided monitor feature, the lags shown there are always 0.

If I look at the Goka code, I think I see why that is, because of
```
func (p *partition) run(ctx context.Context) error {
...
 case *kafka.Message:
....
	p.offset += int64(updates)
	p.hwm = p.offset + 1
....
}
```

and then Goka gest the stats by

```
case <-p.requestStats:
      p.lastStats = newPartitionStats().init(p.stats, p.offset, p.hwm)
```

As I side note, the offset shown in the stats is also different than what I see from the kafka console. (e.g.: it shows I am consuming 18000, but the current group offset as shown in the kafka console is 21000)

The formula I use is `hwm - offset - 1` which always results in 0. I get statistics from processors and views by calling `view.Stats()` and `processor.Stats()`. I get the `offset` and `hwm` from PartitionStats#Table.

Have you encountered this ?

**Comment by mattburman** [comment]
I've also replicated this @cioboteacristian 

Did you ever get a solution for consumer offset lag?

**Comment by frairon** [comment]
@mattburman, we have been working on an improved version of goka that includes improving the Stats. Can you check branch `consumer-group` or tag `v0.9.0-beta2` if it is still an issue for that? I believe that specific bug was resolved there. But if not, let me know and we'll fix it, otherwise it's kind of useless :)
Cheers!

**Comment by mattburman** [comment]
Hi @frairon, sounds great

I've just quickly tried to integrate with my project. I depend on the goka/kafka package for things like `TopicManagerBuilderWithConfig`, `ConsumerBuilderWithConfig`, `WithProducerBuilderWithConfig`  and others

So I get errors installing with go mod vendor:
```
go: finding module for package github.com/lovoo/goka/kafka
go: stash.skybet.net/gs/common-api/internal/domains/group/kafka imports
	github.com/lovoo/goka/kafka: package provided by github.com/lovoo/goka at latest version v0.1.4 but not at required version v0.9.0-beta2
```

I've moved on from working on this at the moment so I don't have a great deal of free time. Just had 30 mins today to check this out. Any pointers on how I can replace the kafka package would be appreciated

**Comment by frairon** [comment]
Sure that's easy. We moved everything that's still needed from goka/kafka to the toplevel goka package. Let me know if you're having more trouble.

**Comment by mattburman** [comment]
Thanks @frairon, glad it was that easy!

I've managed to integrate and use the `partitionStats.Input.OffsetLag` and it does seem to be non-zero so should be more useful now 👍 
I've not got the time to fully test it out to check its correctness but looks good 👍 

I'm excited for the release. I have some work starting within the next few weeks/months to create an opinionated wrapper around goka, like what is suggested on the wiki. Would love to be able to integrate with this new version to include consumer offset lag for prometheus metrics and any other benefits. How's the progress on a full release?

**Comment by frairon** [comment]
I'll close it, seems to be fixed. If not reopen or recreate an issue please :)
