### ISSUE TITLE
Does goka support kafka 2.2.1

### ISSUE THREAD

**Issue by erichatescoding** [lovoo/goka#233]
We are recently working on upgrading Kafka to 2.2.1. I found goka uses sarama under the hood for dealing with kafka. From our application's gopkg.lock, I saw the sarama is on v1.18.0, which does not support kafka 2.2.1.
Anyone has any idea of that?

**Comment by frairon** [comment]
I'll close this one as it's kind of answered in #211. If you're still having issues, feel free to reopen or open another issue.
