### ISSUE TITLE
Sarama 1.27.0 breaks goka installation

### ISSUE THREAD

**Issue by thomashusa** [lovoo/goka#264]
It looks like the release of the [latest version of Sarama](https://github.com/Shopify/sarama/releases/tag/v1.27.0) broke the goka installation. 

To reproduce the issue simply install goka:
```
 $ go get github.com/lovoo/goka
# github.com/lovoo/goka
../../../../pkg/mod/github.com/lovoo/goka@v1.0.0/mockautoconsumers.go:522:23: cannot use session (type *MockConsumerGroupSession) as type sarama.ConsumerGroupSession in argument to handler.Setup:
        *MockConsumerGroupSession does not implement sarama.ConsumerGroupSession (missing Commit method)
../../../../pkg/mod/github.com/lovoo/goka@v1.0.0/mockautoconsumers.go:535:32: cannot use session (type *MockConsumerGroupSession) as type sarama.ConsumerGroupSession in argument to handler.ConsumeClaim:
        *MockConsumerGroupSession does not implement sarama.ConsumerGroupSession (missing Commit method)
../../../../pkg/mod/github.com/lovoo/goka@v1.0.0/mockautoconsumers.go:546:31: cannot use session (type *MockConsumerGroupSession) as type sarama.ConsumerGroupSession in argument to handler.Cleanup:
        *MockConsumerGroupSession does not implement sarama.ConsumerGroupSession (missing Commit method)
```

Downgrading Sarama to `v1.26.4` resolved this issue for me. I just put the following into my go.mod file:

```
replace github.com/Shopify/sarama => github.com/Shopify/sarama v1.26.4
```

**Comment by R053NR07** [comment]
Hey thanks for the reamark. It should be working again.

**Comment by Pantani** [comment]
@R053NR07 the bug persists

**Comment by R053NR07** [comment]
Sorry I forgot the tester... Lets see if #266 works. At least it seems to work on my system.

**Comment by R053NR07** [comment]
If the issue still persists can you please provide another log output? This would really help.

**Comment by troyanov** [comment]
@R053NR07 I can confirm that it works (at least on my machine). 

Would be great if you could add a new `v1.0.1` tag because right now `go get -u github.com/lovoo/goka` gets `v1.0.0` which is broken. Thanks!

**Comment by R053NR07** [comment]
Done. Feel free to check it out. Thanks for your help!
