### ISSUE TITLE
Stuck consumers after rebalance

### ISSUE THREAD

**Issue by rohit-msd** [lovoo/goka#267]
Hi!

We're using goka v0.1.4 for a stateful processing service. We're noticing that after a rebalance, some of the consumers get stuck forever without processing any messages.  We're not seeing the same problem with services which don't have tables associated with them.

NOTE: We don't see the issue with v1.0.1, but it'll take us a while to port all our services to v1.0.1, so just wanted to know if there's anything wrong that we're doing that we can incorporate into our codebase quickly. 

Reproduction steps:

```sh
$ go build -o main ./ 
$ BROKER=<kafka-broker> ./main 2 > consumer-new-1.txt
$ # on a separate terminal
$ BROKER=<kafka-broker> ./main 2 > consumer-new-2.txt
$ # get the tool from https://www.apache.org/dyn/closer.cgi?path=/kafka/2.6.0/kafka_2.12-2.6.0.tgz
$ kafka_2.12-2.5.0/bin/kafka-producer-perf-test.sh --topic results-topic-dummy --num-records 10000 --record-size 1024 --throughput 100 --producer-props bootstrap.servers='kafka-broker'
$ BROKER=<kafka-broker> ./main 2 > consumer-new-3.txt
```

Log files generated by above programs are attached to the issue.

At the end of test, these are the results we have:

| Partition | Topic | Unprocessed messages|
| --- | --- | --- |
| 0 | results-topic-dummy | 0 |
| 1 | results-topic-dummy | 0 |
| 2 | results-topic-dummy | 0 |
| 3 | results-topic-dummy | 1450 |
| 4 | results-topic-dummy | 1528 |
| 5 | results-topic-dummy | 1470 |

The Kafka version we're using is AWS MSK 2.2.1 with 3 brokers and 3 zookeeper instances.

Libraries (from go.mod)
```
github.com/lovoo/goka v0.1.4
github.com/Shopify/sarama v1.26.1
github.com/bsm/sarama-cluster v2.1.15+incompatible
```

```go
package main

import (
	"context"
	"github.com/Shopify/sarama"
	"github.com/lovoo/goka"
	"github.com/lovoo/goka/codec"
	"github.com/lovoo/goka/kafka"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func process(ctx goka.Context, msg interface{}) {
	log.Println("value:", ctx.Offset(), ctx.Partition())
}

func main() {
	sarama.Logger = log.New(os.Stderr, "[Sarama] ", log.Ldate|log.Lmicroseconds)
	// workaround for sarama commitinterval bug
	conf := kafka.NewConfig()
	conf.Consumer.Offsets.CommitInterval = 5 * time.Second
	group := goka.DefineGroup("goka-dummy",
		goka.Input(goka.Stream("results-topic-dummy"), new(codec.String), process),
		goka.Persist(new(codec.String)))

	processor, err := goka.NewProcessor([]string{os.Getenv("BROKER")}, group,
		goka.WithConsumerBuilder(kafka.ConsumerBuilderWithConfig(conf)),
		goka.WithProducerBuilder(kafka.ProducerBuilderWithConfig(conf)),
		goka.WithRebalanceCallback(func(a kafka.Assignment) {
			log.Println("rebalance assignment:", a)
		}))

	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	waiter := make(chan os.Signal, 1)
	signal.Notify(waiter, syscall.SIGINT, syscall.SIGTERM)
	go processor.Run(ctx)
	select {
	case <-waiter:
	case <-ctx.Done():
	}
	cancel()
}
```

[consumer-new-1.txt](https://github.com/lovoo/goka/files/5108464/consumer-new-1.txt)
[consumer-new-2.txt](https://github.com/lovoo/goka/files/5108466/consumer-new-2.txt)
[consumer-new-3.txt](https://github.com/lovoo/goka/files/5108467/consumer-new-3.txt)

**Comment by frairon** [comment]
Hi @rohit-msd, thanks for reporting the issue and all the details, very helpful really! 
To be honest we also had problems with stateful processors on rebalance or even reconnect in case of broker failures.
For lack of resources we never had the time to figure out the real reason and it was hard to reproduce.
Since the processors got stuck only on shutdown in our case, we had a shutdown-timer in our boilerplate code that would kill for the processor if it got stuck. 
So this was the workaround for stuck-on-restart, but for rebalance it's a bit trickier I guess.
One dumb bruteforce approach could be to start a watchdog-timer in the rebalance-callback that gets extended within the processor callback or closes the context to make the processor shutdown if it is stuck. But that's obviously a very hacky solution.

Increasing channel size is probably worth a shot. If there are changes necessary, I'm happy to create a branch so you can create a PR on that. Just let me know.

I haven't tried to reproduce the examples you provided yet, hopefully have some time the next days. I'll let you know if there are any other quick solutions.

**Comment by frairon** [comment]
@rohit-msd, tried your code, awesome work! This could reproduce the bug right away and indeed the workaround you proposed is working. 
After setting the partitionChannelSize to 512 (default sarama buffer is 256), the issue couldn't be reproduced.
So the easiest solution I guess would be to pass `WithPartitionChannelSize(512)` when starting a processor to avoid this.
The other solution is to change goka by defining a higher `defaultPartitionChannelSize`. But I'd prefer not to apply any fixes to outdated versions, unless it's absolutely necessary, so let's go with the processor-option.

If that fixes it for you, feel free to close the issue.

Again, many thanks for the detailed contribution. Made debugging it a whole lot easier!

**Comment by rohit-msd** [comment]
Yes,I've not seen any problems with the workaround till now. I'm attaching a patch in case anyone wants to use that will likely fix the issue but haven't tested completely. 
```
diff --git a/partition.go b/partition.go
index 7462c4b..9565b77 100644
--- a/partition.go
+++ b/partition.go
@@ -161,14 +161,16 @@ func (p *partition) run(ctx context.Context) error {
 		}
 	}()
 
-	// recover the dropped events
-	for _, ev := range p.droppedEvents {
-		select {
-		case p.ch <- ev:
-		case <-ctx.Done():
-			return nil
+	go func() {
+		// recover the dropped events
+		for _, ev := range p.droppedEvents {
+			select {
+			case p.ch <- ev:
+			case <-ctx.Done():
+				return
+			}
 		}
-	}
+	}()
 
 	for {
 		select {
```
