### ISSUE TITLE
Processor fails to start with "resource temporarily unavailable" error

### ISSUE THREAD

**Issue by mrahs** [lovoo/goka#273]
This error happens with processors that have `Join` and/or `Persist` edges which use LevelDB. 

The database is opened in a [separate goroutine](https://github.com/lovoo/goka/blob/master/partition_table.go#L203), but the parent one can [return too early](https://github.com/lovoo/goka/blob/master/partition_table.go#L216) without capturing the db reference. In other words, the database is never closed keeping the lock file acquired and causing subsequent attempts to open the database to fail with `resource temporarily unavailable` error. 

In my case, a partition reassignment canceled the session context before the db was fully open.

I will submit a PR to fix this.

**Comment by adw1n** [comment]
@mrahs this got fixed in https://github.com/lovoo/goka/pull/274, right? Can we close this issue?
