### ISSUE TITLE
ASF trademark

### ISSUE THREAD

**Issue by mjsax** [lovoo/goka#285]
Hi,

I am reaching out on behalf of the Apache Kafka PMC, because the logo of your project violates ASF trademark policies: http://www.apache.org/foundation/marks/faq/#poweredby

While we highly appreciate your project that makes the Apache Kafka eco-system stronger, we need to kindly asked you, to pick a different logo. I would have preferred to reach out via email, but your Github profiles do not include this information. If you have any questions, please reach out to the Apache Kafka PMC via private@kafka.apache.org

Thanks for your understand and collaboration. We wish you all the best for the success of your project.

On behalf of the Apache Kafka PMC,
  -Matthias J. Sax

**Comment by frairon** [comment]
Hi Matthias, 

thanks for the hint, I just removed the logo. 
Hope I didn't miss something. Otherwise let me know.

Best Regards - Franz

**Comment by mjsax** [comment]
Thanks for your swift reply! Not using any logo does of course address the issue.

Thanks for respecting ASF trademarks and your collaboration! Hope you find a good new logo!

-Matthias
