### ISSUE TITLE
How do views scale?

### ISSUE THREAD

**Issue by lumpynifkin** [lovoo/goka#304]
Trying to understand how views are able to scale with increased load. Using the clicks example, lets say I have millions of users that are being clicked on each minute. It seems we are able to scale the view nodes horizontally in order to handle a bunch of requests. But that means each materialized global view node needs to consume all of the changes happening to every user. If I'm getting a 100k clicks a second across all partitions, the view nodes can't possibly keep up and handle the query requests. How is this handled? Do the nodes only process keys when they get a query for that key?

**Comment by frairon** [comment]
Hi @lumpynifkin, the views work bascially what you expected. Each instance has a complete copy of all partitions, so even though horizontal scaling doesn't have limits, the views have limits in terms of updates per second. 
How is this handled? It isn't, we haven't had any issues in this regard yet. Having too many updates is usually handled on application level, e.g. with processors that aggregate for the specific use cases, so the views won't get overloaded. 
I guess for your use case we would need to build some kind of sharding, where we specify which partitions are handled by which view and keep those settings in sync with the load balancer that requests the correct view.
It's probably not even hard to do, just add some options to the view so it's not using all partitions, but as said, there was no need for it yet.

**Comment by WillRemesh** [comment]
Awesome, thanks for the response. I figured it would be that type of solution with the load balancer. Is there any functionality currently built that ensures requests served by the materialized view are up to date with the processor? Possibly using the offset to make sure all events up to a certain point are represented in the view. I guess this could be considered a version of windowing. Looking to make sure update then request workflows will be up to date. If I send a click event, then request the view, is there any way to ensure the click I sent is included in the response?

**Comment by lumpynifkin** [comment]
Awesome, thanks for the response. I figured it would be that type of solution with the load balancer. Is there any functionality currently built that ensures requests served by the materialized view are up to date with the processor? Possibly using the offset to make sure all events up to a certain point are represented in the view. I guess this could be considered a version of windowing. Looking to make sure update then request workflows will be up to date. If I send a click event, then request the view, is there any way to ensure the click I sent is included in the response?

**Comment by frairon** [comment]
Currently there's nothing sophisticated built into the views that could be used to ensure that the messages are up to date. 
There are low level stats however, that contain the offset lag for each partition and could easily be used to build some lag-detection. The main issue here is what to set the threshold to, as it depends on the throughput of the topic. But maybe some very simple metric like "above-std-dev-over-moving-window" would suffice to detect a "lagging" view.

For the second question making sure that a click arrived at the view: I'd say this has to be solved on application level. The input click will have offset x, when the processor adds it to the table, it will have offset y. 
So even a non-lagging view cannot guarantee that the processor has processed that message already.

**Comment by lumpynifkin** [comment]
Thanks for all the info.
