### ISSUE TITLE
goka logging interface

### ISSUE THREAD

**Issue by pfortin-urbn** [lovoo/goka#305]
This is more maybe of an observation than a bug but I was using goka 0.14.0 before and decided to upgrade to 1.0.6 and I found that the experience was mostly painless except for the logger interface which took me a bit of time to wrap my head around.   I needed to use JSON to log into kibana/logstash to achieve best results with searching most of our keys are indexed.  So in version 0.14.0 I used logrus as my basic logger since it filled my enterprise's requirements.

In goka version 1.0.6 the logger interface comes into play and stopped me from passing an instance of logrus directly since it does not implement the `Prefix(string) logger.Logger` method of the interface.  So i had to create my own interface with seems to work currently.   i will post here but I think it's a bit wonly for 1 library to impose a standard in another separate library...

Maybe I was a bit to contrived, i'm posting my wrapper around logrus to fit the goka interface here if there is a more elegant solution please speak up.

Cheers!

```
package new_logger

import (
	"io/ioutil"
	"os"

	"github.com/lovoo/goka/logger"
	log "github.com/sirupsen/logrus"
	"github.com/urbn/gourbnkit/v2/urbnlog"

	"atp_router/app"
	"atp_router/app/logging"
)

type LogrusLogger interface {
	WithFields(fields map[string]interface{}) AtpLogger
	Infoln(args ...interface{})
	Infof(msg string, args ...interface{})
	Info(msg string)
}

type AtpLogger interface {
	logger.Logger
	LogrusLogger
}

// std bridges the logger calls to the logrus library log.
type std struct {
	entry *log.Entry
}

func (s *std) Print(i ...interface{}) {
	s.entry.Print(i)
}

func (s *std) Println(i ...interface{}) {
	s.entry.Println(i)
}

func (s *std) Printf(s2 string, i ...interface{}) {
	s.entry.Printf(s2, i)
}

func (s *std) Debugf(s2 string, i ...interface{}) {
	s.entry.Debugf(s2, i)
}

func (s *std) Panicf(s2 string, i ...interface{}) {
	s.entry.Panicf(s2, i)
}

func (s *std) Infoln(args ...interface{}) {
	s.entry.Infoln(args)
}

func (s *std) Infof(msg string, args ...interface{}) {
	s.entry.Infof(msg, args)
}

func (s *std) Prefix(_ string) logger.Logger {
	return s
}

func (s *std) Info(msg string) {
	s.entry.Info(msg)
}

func (s *std) WithFields(fields map[string]interface{}) AtpLogger {
	newAtpLogger := &std{
		s.entry.WithFields(fields),
	}

	return newAtpLogger
}

var atpLogger *std

var logLevels = map[string]log.Level{
	"DEBUG":   5,
	"INFO":    4,
	"WARNING": 3,
	"ERROR":   2,
}

func GetNewLogger(settings *app.Settings) AtpLogger {
	if atpLogger != nil {
		return atpLogger
	}
	logLevel := logLevels["INFO"]
	dataCenterID := "local"
	outFile := ioutil.Discard
	if settings != nil {
		logLevel = logLevels[settings.LogLevel]
		dataCenterID = settings.DataCenterID
		outFile = os.Stdout
	}
	logger := &log.Logger{
		Out:          outFile,
		Hooks:        nil,
		Formatter:    &logging.NewFormatter{},
		ReportCaller: false,
		Level:        logLevel,
		ExitFunc:     nil,
	}
	entry := logger.WithFields(log.Fields{
		urbnlog.URBN_PRIMARY_DATA_CENTER_ID: dataCenterID,
		urbnlog.SERVICE:                     "atprouter",
		urbnlog.PROCESS:                     os.Args[0],
		urbnlog.PID:                         os.Getpid(),
	})

	atpLogger := &std{
		entry: entry,
	}
	return atpLogger
}
```

**Comment by frairon** [comment]
Thanks a lot for the hint! As discussed in slack we'll take a look and hopefully come up with a better solution in the next days.

**Comment by frairon** [comment]
@pfortin-urbn I have a proposal in [this PR](https://github.com/lovoo/goka/pull/310).
This removes the  prefixing-logic from the interface, which greatly simplifies its usage/replacement by other loggers. Could you check the branch if it would work for you / solve the issue with logrus?
Also I'm not if it's too much of a breaking change to remove the `logging` package and move the logger into main. Any thoughts on that @R053NR07 and @jomaresch?

**Comment by pfortin-urbn** [comment]
@frairon - Just saww this will check it out in the next couple of days sorry for the delay.

**Comment by pfortin-urbn** [comment]
Works for my application!!

**Comment by frairon** [comment]
Merged and released, closing the issue.
