### ISSUE TITLE
Support Kafka headers in tester package

### ISSUE THREAD

**Issue by wwaldner-amtelco** [lovoo/goka#307]
Recently PR #77 was added that allows passing headers to the context emit method.  The same needs to be done for the Tester.Consume(...) method.  In order to write unit tests that can properly test processors that utilize headers in the handling of a message, the tester interface needs to accept and pass headers to processors.

**Comment by wwaldner-amtelco** [comment]
I have created a PR #308 that implements and tests this feature.

**Comment by frairon** [comment]
should be closed, PR is merged. Feel free to reopen/create new issue if there are more problems.
