### ISSUE TITLE
Headers option should append headres not replace them

### ISSUE THREAD

**Issue by mrahs** [lovoo/goka#312]
`WithCtxEmitHeaders` option [currently replaces headers](https://github.com/lovoo/goka/blob/68893ef0b6d9748514f3593445498b592ae3911a/options.go#L534) every time it's called, which means only the last call gets its headers registered. I would expect multiple uses of this option to merge headers instead.

So roughly this:
```
func WithCtxEmitHeaders(headers map[string][]byte) ContextOption{
	return func(opts *ctxOptions){
                for k, v := range headers { opts.emitHeaders[k] = v }
	}
}
```
Instead of this:
```
func WithCtxEmitHeaders(headers map[string][]byte) ContextOption{
	return func(opts *ctxOptions){
		opts.emitHeaders = headers
	}
}
```

**Comment by frairon** [comment]
good point @mrahs, will [this](https://github.com/lovoo/goka/pull/313/files) fix the issue for you?

**Comment by mrahs** [comment]
Yep. Thanks @frairon for the quick fix!

**Comment by frairon** [comment]
Awesome, thanks for the hint. PR is merged, will close this issue.
