### ISSUE TITLE
Question:  Can I have 2 separate input processors

### ISSUE THREAD

**Issue by pfortin-urbn** [lovoo/goka#314]
I have 2 separate inputs:

- input type 1
  - has a view over the output.
  - process A handles the inputs and outputs message A
  - process B handless the filtering of message As for the message A consumers
  
- input type 2
  - does NOT have a view but needs share the view from type 1
  - Process C handless type 2 messages and creates message As and message B (contains several message As)
  - Message As are sent to process B (above) for filtering and will be all filtered out but saved in the view.
  - Process C continues to send messages to a separate outgoing topic

Can you help me design a topology to handle this situation?  Or should I just create two separate applications)

Any help is appreciated

Crude diagram of what I am trying to do

![image](https://user-images.githubusercontent.com/7537534/115119536-d8f7ae00-9f76-11eb-8196-d43929c49ab8.png)

**Comment by frairon** [comment]
@pfortin-urbn 
Sorry for the delay. To be honest, I'm not completely sure what you're trying to achieve here in detail. 
The chart is a great start, but some names/concepts are not really clear.
What I can say for now: no need to have multiple applications, everything can be in one binary, goka does not care about that.

When we design multiple processors and topologies, we start defining the processors in terms of the group graphs later used in goka:
* group name
* input stream(s) (just the topic name, not the codec or message type)
* joined/lookup table(s)
* output stream(s)
* optional persistent table

So for your use case, it looks like we have Processors A, B, C

Processor A:
This one is stateless, only filters the messages and outputs to Processor B
* group-name: processor-a
* input = input1
* output = messageA

Processor B: 
* group-name: processor-b
* input = messageA
* has persisted table, just stores input
(Actually if Processor A and B are like this, they can be joined together)

Processor C:
reads input 2, joins with messageA from view of processor-b-table, output to message-b
* group-name: processor-c
* input = input2
* join/lookup = table of B (i.e. processor-b-table)
* no persistent table
* output = messageB

So I assume the above definition is completely wrong or missing the point, but if we do it that way, it's very easy to translate this into the required group-graphs that set up the network of processors.

Hope that helps a bit. Feel free to post more concrete examples, then we can figure out how to set up the processors.

**Comment by pfortin-urbn** [comment]
Franz,

That's pretty close but not quite, I'll try to add a lot more details here:

So we have our inventory system that publishes messages in real time to my application - that message can contain multiple Skus sources from multiple locations, and the current application breaks that messages into several smaller messages () and passes those to a loopback that then triages the messages and decides wether they need to be forwarded to the main website inventory or not.  That's the left side of my graph above and the topology is:

```	
   return goka.DefineGroup(group,
		goka.Input(goka.Stream(ap.Settings.YantriksTopicName), new(app.AtpMessageCodec), receivers.FullSyncReceiver{
			Settings: ap.Settings,
		}.Do),
		goka.Loop(new(app.AtpMessageCodec), receivers.LoopbackReceiver{
			Logger:         ap.Logger,
			Settings:       ap.Settings,
			InventoryTopic: goka.Stream(ap.Settings.InventoryTopicName),
		}.Do),
		goka.Output(goka.Stream(ap.Settings.InventoryTopicName), new(app.AtpMessageCodec)),
		goka.Persist(new(app.AtpMessageCodec)),
	)
```

Now we need to had a new feed that will publish a new message on a separate topic of a product with their associated Skus  that meeds an update.  This new processor needs to handle the new message that contains the new inventory levels and update the K/V store of the first processor and provide the website with a new message at the product level. 

What I have so far as the topology for app2 is the same as the above processor except that the first input is different.

That's it in a nutshell - I am open to a conversation to explain further if required.   I think I decided on two separate applications so they can be scales separately and and different times.

Thanks a lot for all your help!

Paul

P.S.: The documentation could use some definitions and explanations of what all the `edges` are and how to use them.   The examples are great but knowing when and how to use each edge could be very helpful in designing topologies.

**Comment by pfortin-urbn** [comment]
So we settled on creating a second topic for my first application the one that maintains state and get the second app to create a message with a separate codec that will feed the first application and keep the KTable / K/V store in sync.  The second app will simply have a Lookup to the first application's KTable to determine what it needs to do.
