### ISSUE TITLE
LevelDB's Seek semantics do not honour goka's

### ISSUE THREAD

**Issue by mrahs** [lovoo/goka#318]
Goka's interface requires clients to call `Next` after a successful `Seek` before accessing the key-value pair:
- https://github.com/lovoo/goka/blob/48c2ec23705ff6ea23bb760e832cf2705d559edc/iterator.go#L24
- https://github.com/lovoo/goka/blob/48c2ec23705ff6ea23bb760e832cf2705d559edc/storage/storage.go#L36

LevelDB's interface makes the key-value pair immediately available after a successful `Seek`:
- https://github.com/syndtr/goleveldb/blob/64b5b1c739545ed311fb9d9924d19d188fabdc83/leveldb/iterator/iter.go#L39

Calling `Next` on a leveldb implementation after a successful `Seek` effectively skips an element in the iterator.

I would expect all implementations of the interface to behave the same.

Suggested fix is adding another edge-case to goka's wrapper to skip the first `Next` call after a `Seek`: https://github.com/lovoo/goka/blob/48c2ec23705ff6ea23bb760e832cf2705d559edc/storage/iterator.go#L15

**Comment by frairon** [comment]
Hi Anas, 
awesome observation, I think the Seek was used so rarely that it never occured.
Let's add the edge case. 

Will you give it a shot or should I?

Cheers!

**Comment by frairon** [comment]
the fix is merged, so I'll close the issue.
