### ISSUE TITLE
Remove sarama depency from Callback

### ISSUE THREAD

**Issue by frairon** [lovoo/goka#331]
In this PR https://github.com/lovoo/goka/pull/315/files the headers were added to the view's update callback.

However that means all applications using view callbacks pull sarama-dependency directly into their code, which I'd really like to avoid actually.
Could we maybe do another breaking change and replace that argument with an argument of type `header.Headers` (or `Headers`? 
So the signature could look like
```go
type UpdateCallback func(s storage.Storage, partition int32, key string, value []byte, headers Headers) error
```
The major disadvantage here would be that the view will always create the "header"-map for every message, even if it's being discarded. So maybe an update-context with a getter that creates the headers on demand would even be better, also we would be more flexible for future requirements. But I don't know if that's too much of a breaking change.
E.g. like this:
```go
type CallbackContext interface{
    Headers() Headers
}
type UpdateCallback func(s storage.Storage, partition int32, key string, value []byte, ctx CallbackContext) error
```

It's not a very critical issue, just felt kind of wrong to add the sarama-dependency to our application logic in all components that use the view callback, even though they never used them.

@mrahs as the original author, what do you think?

**Comment by mrahs** [comment]
I agree. My original intent was to avoid updates in existing code that _uses_ the callback. Let's not force an external dependency on implementations. I'll try to put something together this weekend.

**Comment by frairon** [comment]
I didn't mean you to do it :D, just wanted to get your opinion. 
Either solution is probably not too hard to implement, the question is just how much performance overhead we're willing to accept and how annoyed the users will be by the changes. But if you insist on giving it a shot, then I won't be in your way :smile:

**Comment by frairon** [comment]
closing the issue, it's fixed and merged. Many thanks @mrahs
