### ISSUE TITLE
go get package failed

### ISSUE THREAD

**Issue by ouranoshong** [lovoo/goka#371]
problem: go get package failed.

❯ go get -u github.com/lovoo/goka
# github.com/lovoo/goka
../../go/pkg/mod/github.com/lovoo/goka@v1.1.1/mockautoconsumers.go:79:2: cannot use pc (type *MockAutoPartitionConsumer) as type sarama.PartitionConsumer in return argument:
        *MockAutoPartitionConsumer does not implement sarama.PartitionConsumer (missing IsPaused method)

golang env:

❯ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/hong/.cache/go-build"
GOENV="/home/hong/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/hong/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/hong/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/hong/Documents/golang-kafka/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1326561310=/tmp/go-build -gno-record-gcc-switches"

**Comment by frairon** [comment]
fixed in version [v1.1.2](https://github.com/lovoo/goka/releases/tag/v1.1.2)
Thanks a lot for the hint!
