### ISSUE TITLE
Wiki references ZKTopicManagerBuilder but it doesn't exist

### ISSUE THREAD

**Issue by robottheory** [lovoo/goka#381]
The wiki says to use kafka.ZKTopicManagerBuilder if we want the processor to automatically create the topic but this doesn't seem to exist.  Can someone suggest what we are supposed to use instead?

**Comment by frairon** [comment]
Hi @robottheory,

the wiki is kind of outdated but we're continuously working on an improved documentation via github pages. There's small explanation on how to create topics in [First Steps#Creating Kafka Topics](https://lovoo.github.io/goka/docs/getting_started/first_steps/#creating-kafka-topics). However it needs lots of polishing and content, so don't get distracted by the TODOs everywhere :)
