### ISSUE TITLE
RedisIterator skips first key when it.Next() is called

### ISSUE THREAD

**Issue by chrisfjones** [lovoo/goka#394]
The [Processor.VisitValues](https://github.com/lovoo/goka/blob/f0789345dab8cb42671e31ca916cf4e9bd13b186/partition_processor.go#L684) function expects [it.Next()](https://github.com/lovoo/goka/blob/f0789345dab8cb42671e31ca916cf4e9bd13b186/partition_processor.go#L684) to be called before accessing any keys. The `redisIterator` doesn't behave this way and will instead skip over the first key.

**Comment by frairon** [comment]
Oh damn, that's embarassing. That should've been covered by a test. Thanks for the hint, will take care of that as soon as possible. Unless you want to give it a shot :roll_eyes:

**Comment by chrisfjones** [comment]
No worries! I'm working on a PR now, just adding tests 👍

**Comment by frairon** [comment]
Awesome, thanks a lot!

**Comment by chrisfjones** [comment]
Upon further inspection, it appears the contract for storage.Iterator is that `it.Next()` must be called first before accessing. This is how all the other iterators appear to work, so I've just updated `redisIterator` to behave that way in this PR https://github.com/lovoo/goka/pull/392 👍

**Comment by frairon** [comment]
Now that you mention it, there was a similar discussion in [PR 320](https://github.com/lovoo/goka/pull/320#issuecomment-842400750) when fixing differences between different storages using `Seek`. So again, good catch and thanks for the fix :) 

I guess we should improve the iterator here and there:
* better documentation + examples
* define behavior when calling `Value` or `Key` without having called `Next` first
* make sure all supported storages are maintained and tested
