### ISSUE TITLE
Link to blog post is dead

### ISSUE THREAD

**Issue by rupurt** [lovoo/goka#405]
Howdy,

The link to the blog post in the README appears dead https://lovoodotblog.wordpress.com/2017/05/23/goka/. Unfortunately it looks like there are also no historical snapshots https://archive.ph/3ceXp.

**Comment by norbertklawikowski** [comment]
Hi @rupurt,

Thanks for the hint, unfortunately the blog content is lost and the README is not yet updated. I will remove the link from the README.

A part of the blog post exists in the Github Pages for Goka:

https://lovoo.github.io/goka/docs/guide/02_overview

The first section has a diagram and a bit more info about the components of Goka.

The Github Pages are still work in progress, they will be linked to when ready.
