### ISSUE TITLE
Provide examples of lookups

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#79]
I couldn't find any example or documentation about how to use lookups (`goka.Lookup`, `ctx.Lookup`).

I'm not sure my use case is possible, but I would like to have something similar to Kafka Streams GlobalKTable, which is a state of a topic across ALL it's partitions. Useful for some small set of lookup values that should not be co-partitioned with the main processor's topic.

So for example I have a topic called `cities` which is a compacted topic of ID as key and Name as value. And then I have a processor for `users` topic with user's ID as key and user properties as value (city id is one of the properties).

So for each user I want to lookup a city name by this user's city_id, but I don't want to partition users topic by city ID because it doesn't make sense. So cities topic should be processed entirely to fill the lookup table.

Is it currently possible with Goka?

**Comment by db7** [comment]
Yes, that is possible with "lookup tables".

When creating your processor, add something like `Lookup(Table("some-table"), codec)` to the graph description. Then in the callbacks you can retrieve entries from the table by calling `ctx.Lookup("some-table", "some-key")`.

And you are right. We should have an example for that. I actually have some drafts somewhere, but someone would need to review that. Would you mind reviewing some new examples?

**Comment by burdiyan** [comment]
@db7 Sure, I'm happy to review that.

**Comment by db7** [comment]
@burdiyan please check PR #88.

**Comment by burdiyan** [comment]
Closing this issue, as more examples are coming.
