### ISSUE TITLE
Add blocking recovered method

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#80]
Right now the `Recovered` method on `goka.View` and other objects is returning a `bool`. Although it's helpful for most of the applications being able to block until it's ready.

What do you think about introducing additional method, like `Ready` that would return `<-chan struct{}` instead, so that the caller can block until there is something on the channel?

Behind the scenes, this method could poll the `Recovered` method internally in a goroutine with some default sleep value, until `Recovered` returns true.

**Comment by frairon** [comment]
Almost every time when you want to wait/block for something, you need a timeout. So just returning the channel is only kind of half the way, I think. 
And if you do need to add a timeout, then calling the Recovered-Method repeatedly in a go-routine is very little code in addition, like:

```golang
recovered := make(chan struct{})
go func(){
    for !view.Recovered(){
        time.Sleep(1)
    }
    close(recovered)
}()
select{
    case <-recovered:
        // recovered
    case <-time.NewTimer(timeout).C:
        // recovery not done, timed out
}
```

So my suggestion is: either leave the polling entirely to the caller, or include the timeout in the `Ready` method, which then blocks until its done (or timed out).
Something like this:

```golang
func (v *View) Ready(timeout time.Duration) bool {
	recovered := make(chan struct{})
	go func() {
		for !v.Recovered() {
			time.Sleep(1)
		}
		close(recovered)
	}()
	select {
	case <-recovered:
		// recovered
		return true
	case <-time.NewTimer(timeout).C:
		// recovery not done, timed out
		return false
	}
}
```

What do you think? Any other alternatives that make more sense?

**Comment by burdiyan** [comment]
Yeah, that is actually something that I realized afterwards. I would suggest adding a `context.Context` since that is the recommended approach for canceling stuff, pushed by the community.

I ended up with this implementation, that i use in my projects:

```
import (
	"context"

	"golang.org/x/sync/errgroup"
)

type recoverer interface {
	Recovered() bool
}

// Ready waits until all of the passed dependencies
// are recovered, or context is canceled.
func Ready(ctx context.Context, rs ...recoverer) error {
	g, gctx := errgroup.WithContext(ctx)

	for _, r := range rs {
		g.Go(func() error {
			for {
				select {
				case <-gctx.Done():
					return gctx.Err()
				default:
					if r.Recovered() {
						return nil
					}
				}
			}
		})
	}

	return g.Wait()
}
```

**Comment by db7** [comment]
I find this solution with `errgroup` pretty elegant.

**Comment by frairon** [comment]
I'll close it for lack of activity. Looks like a duplicate of #237 which should be fixed in the new versions. If you have further requirements, feel free to comment on that issue or create a new one.
