### ISSUE TITLE
Issues getting value from view

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#83]
I'm facing weird issue with views:

I have a topic with 10 partitions, where each message has a string key.

I create a view for this topic, wait until view is recovered, than do `Get` for a key that I'm really sure exists, and I get nil value and nil error.

BUT, the weirdest thing is that when I create an iterator for that view, I see that there is actually a message for this key.

And even after iterating, when I try to access the same key, I continue seeing nil value and nil error.

Does anyone know what can I be missing?

**Comment by burdiyan** [comment]
Well, there is a problem with that when you use the view as lookup. There is no way to pass hasher to the lookup view, and the hasher you pass to the processor, is not propagated to the underlying view.

**Comment by burdiyan** [comment]
I'll create a separate issue for that. But on the other hand let me know you'd like to see contribution for a JVM compatible hasher. I think it's useful if you're using some of the tools from the Kafka ecosystem, like Kafka Connect.

**Comment by db7** [comment]
It would be nice to have the murmur2 hasher available in goka.

**Comment by burdiyan** [comment]
I'll try to submit a PR as soon as I can. For now, I have it implemented in my `kafkautil` library: https://github.com/burdiyan/kafkautil/blob/master/partitioner.go#L27 for those who are interested.
