### ISSUE TITLE
Allow passing custom hasher for graph dependencies

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#84]
Right now there is no way to pass a custom hasher for views (for example) when you configure `Lookup` edges. So, if your topic you use for view is not partitioned using default Sarama's hasher, it will never find the correct value.

The hasher passed to the processor of the graph is not propagated to the view (which can be the simplest solution, although not always the right one, since you can you different hashers for main input and lookups).

I believe there should be a way to pass corresponding options to each edge of the graph. Using variadic parameters should not break the compatibility.

**Comment by burdiyan** [comment]
Another option can be to enable the way to pass view instances that are preconfigured to the graph.

**Comment by burdiyan** [comment]
Finally probably the easiest option would be to make `goka.DefaultHasher` a global variable that is a function instead of plain function. This way a user can override the default hasher, because most of the times one would only use one hasher per project.

**Comment by db7** [comment]
That is a bug, nice catch.

[This](https://github.com/lovoo/goka/blob/6f74b5204841d4eef91ff06218ee5662702ab71b/processor.go#L101) line should pass the processor hasher as option the the lookup table.

Adding an `EdgeOption` is a nice thing, but it would take more work and I think we should fix the above line anyway. The global variable solution sounds not necessary to me.

**Comment by burdiyan** [comment]
It seems like this line mentioned above is already in master.

On the other hand, am I right assuming that passing `WithHasher` to `NewProcessor` will apply this hasher to all the of the producers on the dependent graph?

If so, I believe this issue can be closed.

**Comment by db7** [comment]
You are right, the producer created inside the processor should already get the right hasher -- unless one overwrites the producer with `WithProducer` option.

However, the issue you pointed before is still a bug for lookup tables, because there we need the hasher as well. We need the hasher to figure out in which partition the keys are. #91 should resolve the issue for lookup views.
