### ISSUE TITLE
Changing Sarama Version in Emitter

### ISSUE THREAD

**Issue by jbpin** [lovoo/goka#87]
Is that the only way to change config Version for Sarama producer ?

```go
hasher := goka.DefaultHasher()
partitioner := sarama.NewCustomHashPartitioner(hasher)
config := kafka.CreateDefaultSaramaConfig("goka", partitioner, metrics.DefaultRegistry)
config.Version = sarama.V1_0_0_0
producer, err := kafka.NewProducer(brokers, &config.Config, logger.NewLogger(log.WithField("app", "service")))

if err != nil {
    return nil, err
}
emitter, err := goka.NewEmitter(brokers, goka.Stream(topic), new(codec.Proto), goka.WithEmitterProducer(producer))
```

**Comment by db7** [comment]
Yes, so far that is the only way. 

Btw, we tried using 1.0.0 in our test cluster, but had several performance issues. I'd be interested to know if you have performance issues too. The confluent library with Kafka 1.0.0 performed better for us  (there some experimental code in `kafka/confluent` for the consumer side), but we decided to stick to 0.10.2 for now.

**Comment by jbpin** [comment]
Hi @db7,

It's good to know, thanks for your feedback. Unfortunately, I didn't start performance testing. But I'll keep you posted. FYI I'm using Confluence 4.0.0 in my test cluster on Kubernetes.

**Comment by db7** [comment]
Should we enable the wiki and add such snippet there?

**Comment by jbpin** [comment]
I think it will have save me time to have access to this. So yep
definitely.

**Comment by db7** [comment]
I'll write some examples in the Wiki for setting the builders for storage, consumers and producers. Meanwhile, I did some cleanup of the builders in PR #92. Perhaps you have the chance to take a look?

Once that PR gets in, your example above should look like:
```go
config := kafka.CreateDefaultConfig("client-id")
config.Version = sarama.V1_0_0_0
emitter, err := goka.NewEmitter(brokers, goka.Stream(topic), new(codec.Proto), 
     goka.WithEmitterProducerBuilder(kafka.ProducerBuilderWithConfig(config)))
```

**Comment by db7** [comment]
The PR is not merged and the notes are in the wiki. Closing this issue.
