### ISSUE TITLE
Initial offset handling

### ISSUE THREAD

**Issue by burdiyan** [lovoo/goka#97]
Docs says that Goka will read from the newest offset for streams (`goka.Input`) and same thing appears in the log when processor starts (something like map[0:-1]). 

Otherwise, for a freshly created topic, and for consumer group ID that never existed in this broker, my processor consumes all the messages from the beginning of the topic).

This is just to understand what is the correct behavior and fix docs if there’s an error.

**Comment by db7** [comment]
As you say, the intention is:
- if the consumer group never committed any offset of a stream, then the stream are read from the newest;
- tables are consumed from the oldest or from the offset stored in the local storage if any.

Can you double check that your consumer group is new? (perhaps try a new consumer group) Otherwise, this is a bug.

**Comment by burdiyan** [comment]
@db7 just double checked that. New broker, new topic, sent some messages, then started new goka processor with brand new consumer group name, and topic was consumed from the beginning.

**Comment by db7** [comment]
Thanks for checking that again. That's a bug, I'll fix it this week.

**Comment by burdiyan** [comment]
If I really want it to be processed from the beginning (like it does right now) the right way would be to pass custom consumer builder, right?

**Comment by db7** [comment]
That would be the idea. We just need to ensure that tables will always be read from the oldest and streams from the value passed in the config.

**Comment by burdiyan** [comment]
@db7 

>We just need to ensure that tables will always be read from the oldest and streams from the value passed in the config.

When you say this, does it already work like this?

**Comment by db7** [comment]
This line in PR #100 takes the config passed to the builder and overwrites it with offsetoldest. That new config is passed to the simple consumer, which is the one reading from trables.

https://github.com/lovoo/goka/pull/100/files#diff-57960cc1ee87fab707306aab51440a91R69
